services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      # - your-service
      - user-service

  # This is a Template for copypasting
  # Don't forget to: 
  # 1. Change `your_service` and `YOUR_SERVICE_PORT`
  # 2. Add a port for your service in .env file
  # 3. Add a new rule in `nginx/nginx.conf` for your service

  # your-service:
  #   build:
  #     context: ./backend/your_service
  #   ports:
  #     - ${YOUR_SERVICE_PORT}
  #   environment:
  #     - PORT=${YOUR_SERVICE_PORT}
  #     - DB_HOST=db
  #     - DB_PORT=5432

  auth-service:
    build:
      context: ./backend/auth
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - DB_HOST=auth_db
      - DB_PORT=5433
      - DB_NAME=auth_db
      - DB_USER=authuser
      - DB_PASSWORD=authpass
    depends_on:
      - db-auth
    ports:
      - ${AUTH_SERVICE_PORT}
    

  user-service:
    build:
      context: ./backend/users
    ports:
      - ${USER_SERVICE_PORT}
    environment:
      - PORT=${USER_SERVICE_PORT}
      - DB_HOST=db
      - DB_PORT=5432

  # Main App's Postgres DB
  # You can add a separate DB (with different port) for your service, if necessary.
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  db-auth:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=authuser
      - POSTGRES_PASSWORD=authpass
    ports:
      - "5433:5433"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  db-data:
  auth_db_data:
